name = "kaituoyishi"
compatibility_date = "2026-06-03"
pages_build_output_dir = "dist"

[vars]
ONLINE_SESSIONS_KV_PREFIX = "kaituoyishi/online"

[[kv_namespaces]]
binding = "ONLINE_SESSIONS_KV"
id = "b7b54dfe1f914e7ea549cdfe67c7ba1e"
